baseurl = "https://dwrtc.net/"
theme = "book"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "DWRTC contributors"
title = "DWRTC"
disqusshortname = ""
pluralizelisttitles = false

[params]
BookMenuBundle = "/docs/menu"
